### ISSUE TITLE
Docker下 System.Drawing.Image.FromFile 不可用

### ISSUE THREAD

**Issue by yiyungent** [yiyungent/SimCaptcha#6]
![image](https://user-images.githubusercontent.com/16939388/107360483-f476b080-6b10-11eb-9885-9b22c1724ed4.png)

```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromFile(String filename, IntPtr& image)
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromFile(String filename)
   at SimCaptcha.AspNetCore.AspNetCoreVCodeImage.Create(String code, Int32 width, Int32 height) in /src/src/SimCaptcha.AspNetCore/AspNetCoreVCodeImage.cs:line 54
   at SimCaptcha.SimCaptchaService.CreateVCodeImg() in /src/src/SimCaptcha/SimCaptchaService.cs:line 484
   at SimCaptcha.SimCaptchaService.VCode() in /src/src/SimCaptcha/SimCaptchaService.cs:line 408
```

文件位置：
`src/SimCaptcha.AspNetCore/AspNetCoreVCodeImage.cs:line 54`

```C#
var imageStream = Image.FromFile(randomImgFile);
```

**Comment by yiyungent** [comment]
Windows 10 下一切正常

**Comment by yiyungent** [comment]
参考：

- [Asp.Net Core使用System.Drawing.Common部署到docker报错问题 - SunnyTrudeau - 博客园](https://www.cnblogs.com/sunnytrudeau/p/9384620.html)
- [.NET Core使用System.Drawing.Common时找不到libgdiplus的问题_已解决_博问_博客园](https://q.cnblogs.com/q/103863/)
