### ISSUE TITLE
Docker下 | 效验失败 | System.Net.WebException: Cannot assign requested address

### ISSUE THREAD

**Issue by yiyungent** [yiyungent/SimCaptcha#8]
`System.Net.WebException: Cannot assign requested address`

```
System.Net.WebException: Cannot assign requested address Cannot assign requested address
 ---> System.Net.Http.HttpRequestException: Cannot assign requested address
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at SimCaptcha.Common.HttpAide.HttpPost(String url, String postDataStr, StringBuilder responseHeadersSb, String[] headers, WebProxy proxy) in /src/src/SimCaptcha/Common/HttpAide.cs:line 184
   at SimCaptcha.SimCaptchaClient.Verify(String ticket, String userId, String userIp) in /src/src/SimCaptcha/SimCaptchaClient.cs:line 84
```

![image](https://user-images.githubusercontent.com/16939388/107475991-f93e7180-6baf-11eb-880a-ac4374c6341b.png)

**Comment by yiyungent** [comment]
初步判定是因为容器之间彼此隔离，无法通信导致 客户端容器 无法 HTTP 请求 验证码服务端容器，

参考：

- [docker如何进行同主机下容器间的互相通信?(初学菜鸟)？ - 知乎](https://www.zhihu.com/question/267974568/answer/332187314)
- [docker中容器之间通信方式_谦190的博客-CSDN博客_docker 容器之间通信](https://blog.csdn.net/u013355826/article/details/84987233)
- [Docker之容器互联实现容器间通信-Hello,World!-51CTO博客](https://blog.51cto.com/bovin/2170589)
- [docker容器之间的通信 - 豆浆D - 博客园](https://www.cnblogs.com/soymilk2019/p/11553541.html)
- [访问docker主机时java.net.SocketException - IT屋-程序员软件开发技术分享社区](https://www.it1352.com/648022.html)

**Comment by yiyungent** [comment]
解决：
将两个容器处于同一 network（bridge）即可，再通过容器名访问，例如: simcaptcha-container:80
